stages:
  gym_test:
    cmd: python3 src/gym_test.py
    deps: 
    - src/gym_test.py
    - src/utils/anns.py
    - src/utils/action_noise.py
    - src/utils/params.py
    - src/agents/ddpg.py
    outs:
    - models/actor_ddpg-${gym_test.environment}.hdf5
    - models/critic_ddpg-${gym_test.environment}.hdf5
    params:
    - gym_test.environment
    - gym_test.critic_lr
    - gym_test.actor_lr
    - gym_test.save_models
    - gym_test.batch_size
    - gym_test.buffer_capacity
    - gym_test.sigma
    - gym_test.tau
    - gym_test.n_training_steps
    - gym_test.warm_up_steps
    - gym_test.clip_gradients
    - gym_test.log_freq
    - gym_test.eval_episodes
    - gym_test.learn_freq
    - gym_test.performance_th
    metrics:
    - evaluation/metrics_ddpg-${gym_test.environment}.json:
        cache: False
  render:
    cmd: python3 src/render.py
    deps:
    - src/render.py
    - models/actor_ddpg-${gym_test.environment}.hdf5
    - models/critic_ddpg-${gym_test.environment}.hdf5
    - src/utils/visualization.py
    plots:
    - evaluation/${gym_test.environment}.gif:
        cache: false
    params:
    - gym_test.bnorm
    - gym_test.environment
    - render.episodes
  baseline:
    cmd: python3 src/baseline.py
    deps: 
    - src/baseline.py
    - src/utils/action_noise.py
    - src/utils/params.py
    outs:
    - models/ddpg-${gym_test.environment}-baseline.zip
    params:
    - baseline.environment
    - baseline.lr
    - baseline.save_models
    - baseline.batch_size
    - baseline.buffer_capacity
    - baseline.sigma
    - baseline.tau
    - baseline.n_training_steps
    - baseline.log_freq
    - baseline.eval_episodes
    - baseline.warm_up_steps
    - baseline.learn_freq
    metrics:
    - evaluation/metrics_ddpg-${gym_test.environment}-baseline.json:
        cache: False
  render_baseline:
    cmd: python3 src/render_baseline.py
    deps:
    - src/render_baseline.py
    - src/utils/evaluation.py
    - models/ddpg-${gym_test.environment}-baseline.zip
    - src/utils/visualization.py
    plots:
    - evaluation/${gym_test.environment}-baseline.gif:
        cache: false
    params:
    - gym_test.bnorm
    - gym_test.environment
    - render_baseline.episodes