gym_test:
  environment: "Pendulum-v1"
  critic_lr: 5e-4
  actor_lr: 1e-4
  save_models: True
  batch_size: 64
  buffer_capacity: 40e3
  sigma: 0.2
  tau: 3e-3
  n_training_steps: 500000
  warm_up_steps: 1000
  clip_gradients: False
  log_freq: 25
  eval_episodes: 25
  save_best: False
  learn_freq: 2
  performance_th: -170

baseline:
  environment: "Pendulum-v1"
  lr: 1e-4
  save_models: True
  batch_size: 64
  buffer_capacity: 40e3
  sigma: 0.2
  tau: 3e-3
  n_training_steps: 500000
  log_freq: 25
  eval_episodes: 30
  warm_up_steps: 1000
  learn_freq: 2

render:
  episodes: 5

render_baseline:
  episodes: 5
